### PR TITLE
Self host fonts

### PR DESCRIPTION
**Pull request by dkellner**

### CODE REVIEW

**Comment by dkellner** [comment]
I just realize we maybe should provide the font's licence if we host it ourselves. I will take care of that and update the PR.

**Comment by dkellner** [comment]
As far as I unterstand https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web correctly, we have to state the fonts licence on our website. Will we include an imprint or similar page where we could do that? If not, is a small text at the bottom of every page like this ok?

"The font "Overpass" is Copyright (c) 2016 by Red Hat, Inc and is licensed under the SIL Open Font License, Version 1.1."

**Comment by dkellner** [comment]
Ok, the FAQ at https://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web#e71fabc0 states there is no acknowledgement required. I will still include a short comment in `fonts.css`.

**Comment by Twissi** [comment]
Looks great!

**Pull request merged**
