### PR TITLE
Add a skills section

### LINKED ISSUE #11: Add call to action on the page
This should also include the group of persons who can take part (designers, coders, non-techpeople...)

### PR DESCRIPTION
**Pull request by markusphil**
With cta to fix #11

### CODE REVIEW

**Comment by Twissi** [comment]
I love that hover animation 😍

**Comment by Twissi** [comment]
@markusphil because the extra nav item the layout breaks at 1109width and 714px width

**Comment by markusphil** [comment]
@Twissi oh thanks for checking that! Hmmm... maybe we could put the NGOs and Partners together as both are rather small sections. What do you think?

**Comment by normade** [comment]
@markusphil NGO's will hopefully grow soon, as we will add a description of them etc. @danmcatee added some changes too, could you please merge the master in your branch again?

**Comment by normade** [comment]
@markusphil we will need to add sponsors to the page too, so another nav item will appear. Is there a way to have a burger menu for < desktop sizes?

**Comment by markusphil** [comment]
Sure it is! :) But actually I'm not that sure if it'll get a little confusing for the visitors to have that many nav links :thinking:

**Comment by normade** [comment]
@markusphil yes, not optimal, but we need NGOs, Partners and sponsors. Could maybe get rid of the partners link in the nav and just display them like so.

**Comment by markusphil** [comment]
Ups I just realised that a rebase doesn't work that nice for an open pull request! 😅 Sorry, I'm still learning how to git! 🙈 

@normade I removed the link to the skill section for now. I think the improved navigation should be done in a different issue.

**Comment by normade** [comment]
@markusphil yes, good point, I agree, thanks for adding the issue #31 👍

**Pull request merged**
